-- ============================================================================
-- GIC APPRENTICE LMS — MODULE 26 CONTENT
-- Reconciliation & Operations Controls
-- ============================================================================
update public.modules set
  title = 'Reconciliation & Operations Controls',
  competency_id = 'OJL-17',
  ri_hours = 0,
  ojl_hours = 80,
  short_description = 'Reconcile what the firm''s systems say with what the custodian''s records say — daily, monthly, and annually — and build the operational controls that catch errors before they become incidents.',
  learning_objectives = ARRAY[
    'Perform daily, monthly, and annual reconciliation between firm and custodial records',
    'Identify and resolve common reconciliation breaks',
    'Calculate and apply advisory fees accurately',
    'Process corporate actions correctly',
    'Build segregation-of-duties and audit-trail controls appropriate to the firm''s size'
  ],
  content = $jsonb$
  {
    "lessons": [
      {
        "id": "lesson-1",
        "title": "Reconciliation — Why It Exists and What It Catches",
        "summary": "Reconciliation is the discipline of comparing what the firm thinks it has to what the custodian says it has — and chasing down every difference. It is the operational backbone of trustworthy reporting.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "A firm's internal portfolio management system (PMS) tracks positions, transactions, cash flows, performance, and fees. The custodian's system tracks the same things. The two systems should always agree. They sometimes do not — due to delayed feeds, manual entries, corporate actions, fee accruals, or genuine errors. Reconciliation is the practice of comparing the two records, identifying every difference, and resolving each one. Done daily, reconciliation catches errors when they are cheap to fix. Done poorly or rarely, errors compound and reports lose credibility."},
          {"type": "subheading", "content": "What reconciliation catches"},
          {"type": "list", "items": [
            "Trades placed but not reflected in the PMS (or vice versa)",
            "Position quantity discrepancies — a corporate action processed differently in the two systems",
            "Cost basis differences — particularly after wash-sale adjustments, return-of-capital distributions, or transfers in from external accounts",
            "Cash balance differences — a fee accrued in the PMS but not yet debited at the custodian (or vice versa)",
            "Income discrepancies — a dividend posted on different dates in the two systems",
            "Pricing discrepancies — particularly for less liquid securities where the PMS and custodian use different pricing sources",
            "Account-level discrepancies — accounts that exist in one system but not the other (transfers in or out, account closures)"
          ]},
          {"type": "subheading", "content": "Daily reconciliation"},
          {"type": "paragraph", "content": "At the start of every business day, the firm's operations team (or, at smaller firms, the apprentice or operations-aware advisor) compares the prior day's positions and transactions between the PMS and the custodian. Modern PMS platforms automate most of this — they ingest the custodian's feed each night and produce an exception report showing only items that did not auto-reconcile. The work is in resolving the exceptions, not in checking every position manually. Common patterns: a manual trade entered yesterday and not yet flowing through correctly; a corporate action that posted overnight; a fee accrual not yet matched against the custodian's debit."},
          {"type": "subheading", "content": "Monthly reconciliation"},
          {"type": "paragraph", "content": "At month-end, a more comprehensive reconciliation: full position match, cash match, fee accrual match, performance calculation tie-out. The monthly reconciliation produces the foundation for client statements and performance reporting (Module 22). Any unresolved breaks at month-end must be documented and tracked to resolution — they cannot be ignored or hidden. At many firms, the operations team produces a monthly reconciliation report that is signed off by the compliance officer or operations manager."},
          {"type": "subheading", "content": "Annual reconciliation"},
          {"type": "paragraph", "content": "At year-end, on top of the monthly reconciliation, there is a comprehensive tax-level reconciliation: realized gains/losses match between PMS and custodian; cost basis for each lot matches; income types match (dividends, qualified dividends, interest, return of capital); tax-reportable transactions match. The custodian's 1099 reports are the official tax documents — the PMS records should agree. Discrepancies must be resolved before tax-reporting season begins, both because corrections after tax filing are expensive and because mismatched records destroy CPA workflows."},
          {"type": "callout", "kind": "key", "content": "The custodian's records are the official truth. If the PMS disagrees, fix the PMS — not the other way around. Clients see the custodian's statement; their reality is what the custodian says it is."},
          {"type": "subheading", "content": "Tools and automation"},
          {"type": "paragraph", "content": "Most modern advisory firms use a portfolio management system (Orion, Tamarac, Black Diamond, Addepar, others) that automates the bulk of reconciliation through automated feeds from the custodian. The technology handles the routine; humans handle the exceptions. An exception is any item that did not auto-reconcile. The discipline is in the exception workflow: investigate, identify the cause, correct in the appropriate system, document the resolution. Exceptions that linger are operational debt — they accumulate until they become incidents."},
          {"type": "case_study", "title": "The cost basis discrepancy", "scenario": "An apprentice notices a daily reconciliation exception: cost basis on a tax lot of VTI in Naomi's taxable account is $245 per share in the PMS but $241 per share at the custodian. The difference is $4 per share across 252 shares — $1,008 of cost basis difference. Investigation: VTI paid a small return-of-capital distribution earlier in the year. The custodian's system reduced cost basis by the ROC amount; the PMS did not pick up the adjustment correctly. The apprentice initiates a basis adjustment in the PMS to align with the custodian's record, documents the reason, and reports the exception type to the operations manager for systemic review (because the issue likely affected other accounts with the same security).", "discussion": "A $1,008 cost basis difference seems trivial — until tax-loss harvesting decisions or capital gains calculations depend on it. The same systemic issue across 50 accounts is meaningful. Daily reconciliation caught the issue when it was a single-account fix; without the discipline, it would have surfaced at tax time across many accounts."}
        ]
      },
      {
        "id": "lesson-2",
        "title": "Common Reconciliation Breaks and How to Resolve Them",
        "summary": "Knowing the typical break patterns lets you triage exceptions quickly. Most breaks fall into a few recurring categories with well-understood resolution paths.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "Reconciliation exceptions are not all created equal. Some are routine and self-resolving by the next day. Some require active intervention. Some indicate a deeper systemic issue. Triaging exceptions efficiently means recognizing the pattern, applying the standard resolution, and escalating only what genuinely needs investigation."},
          {"type": "subheading", "content": "Timing breaks — usually self-resolving"},
          {"type": "paragraph", "content": "Most reconciliation breaks are timing differences that resolve themselves within 1-2 business days. A trade placed late on Friday may post to the custodian's system Saturday and to the PMS's automated feed Monday morning. A dividend ex-date may produce the dividend in the PMS on the ex-date but at the custodian on the pay-date. These breaks resolve themselves — but you should still note them as expected breaks so they do not get lost in the exception report."},
          {"type": "subheading", "content": "Corporate actions — the largest single category of breaks"},
          {"type": "glossary", "terms": [
            {"term": "Cash dividend", "definition": "A simple distribution of cash to shareholders. Reconciles easily in most systems."},
            {"term": "Stock dividend", "definition": "Additional shares of the same security distributed as a dividend. Requires the PMS to add the new shares at the correct basis."},
            {"term": "Stock split", "definition": "Existing shares split into a larger number; per-share price adjusted proportionally. Position quantity and cost basis per share both change."},
            {"term": "Reverse split", "definition": "Existing shares consolidated into a smaller number; per-share price adjusted up. Often associated with fractional share roundings."},
            {"term": "Spin-off", "definition": "A company distributes shares of a subsidiary to existing shareholders. Cost basis allocation between the original and spun-off security is required."},
            {"term": "Merger", "definition": "Two companies combine; shares of the acquired company become shares of the acquirer or cash. Tax treatment varies."},
            {"term": "Return of capital (ROC)", "definition": "A distribution that is treated as a return of the investor's basis rather than income. Reduces the cost basis of the position rather than being taxed as a dividend."},
            {"term": "Tender offer", "definition": "An offer to buy shares from existing holders at a stated price. Acceptance requires action; declination is the default."}
          ]},
          {"type": "subheading", "content": "How corporate actions create breaks"},
          {"type": "paragraph", "content": "Custodians typically process corporate actions on their announced effective dates with their own data sources. PMS platforms ingest corporate action data from third-party feeds (sometimes the same provider, sometimes different) that may have slight timing or methodology differences. A return of capital distribution might be classified as a dividend by the PMS until the security's annual tax characterization is finalized. A spin-off might post differently based on different basis allocation methodologies. Most of these resolve when the tax year's final classifications are published — but until then, reconciliation requires monitoring and sometimes manual adjustment."},
          {"type": "subheading", "content": "Cash breaks"},
          {"type": "paragraph", "content": "Cash differences between PMS and custodian are usually small but worth tracking. Common sources: advisory fee accruals (PMS books the fee as it is earned; custodian debits when the fee is actually charged); interest accrual timing on bonds (PMS uses straight-line; custodian uses actual coupon dates); ACH transfers in flight (the PMS may have recorded the transfer at initiation; the custodian recognizes it on settlement); pending distributions (a trade in process where cash will arrive). Cash breaks usually resolve within days; sustained cash breaks indicate a more meaningful issue."},
          {"type": "subheading", "content": "Position breaks — the highest-priority category"},
          {"type": "paragraph", "content": "A position quantity discrepancy — the firm thinks the client owns 252 shares of VTI, the custodian shows 250 — is the most serious type of break. It can indicate a real operational error: a trade that did not actually execute, a transfer error, a manual entry mistake. Investigate position breaks immediately. Do not let a position quantity break sit overnight without explanation. Either the client's wealth is mismeasured (you are reporting positions they do not own or missing positions they do) or there is an operational failure that will surface in some other way."},
          {"type": "callout", "kind": "warn", "content": "Any position quantity break that cannot be explained within the trading day is an escalation event. Document, investigate, involve operations and compliance — do not move on until resolved."},
          {"type": "subheading", "content": "Resolving the break — fix in the right system"},
          {"type": "paragraph", "content": "When a break is identified and the cause understood, the fix goes in the system that was wrong. If the PMS missed an entry, post the entry in the PMS to align with the custodian. If the custodian's data feed had a glitch, work with the custodian to correct (rare but possible). Do not adjust the PMS to mask a real issue. The audit trail should show what was changed, when, by whom, and why. PMS platforms log these adjustments automatically."},
          {"type": "case_study", "title": "Marcus and Tasha's spin-off", "scenario": "A company Marcus owns through a single-stock position spins off a subsidiary. Each share of the parent company also receives a fractional share of the spin-off. The custodian processes the corporate action: original position retained, new spin-off position created, cost basis allocated 87% to original and 13% to spin-off (per the company's IRS Form 8937 guidance). The PMS, however, uses a third-party data provider that initially allocates 90/10. Daily reconciliation flags the basis discrepancy. The apprentice researches the company's filing, confirms the 87/13 allocation is correct per IRS guidance, and adjusts the PMS to align with the custodian. Documents the source (company's Form 8937) and the resolution. Reports the data feed discrepancy to the operations manager for review with the third-party provider.", "discussion": "Corporate actions are operationally complex. Reconciliation catches the discrepancies; research identifies the correct treatment; fix in the appropriate system; document the source. The audit trail months later shows exactly what was decided and why."}
        ]
      },
      {
        "id": "lesson-3",
        "title": "Advisory Fee Calculation and Application",
        "summary": "How and when advisory fees get charged is governed by the advisory agreement and the firm's billing process. Getting fees right — and reconciling them precisely — is fundamental operational integrity.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "Advisory fees are how the firm gets paid. The advisory agreement specifies the fee schedule, billing frequency, calculation method, and authorization for the custodian to debit the fee directly from client accounts. Calculating fees accurately, applying them correctly, and reconciling them against the firm's expectations is one of the most-watched operational controls — both because fee errors generate immediate client complaints when overcharged and immediate revenue loss when undercharged."},
          {"type": "subheading", "content": "Fee structures"},
          {"type": "list", "items": [
            "Tiered AUM percentage — different rates apply to different brackets of AUM (e.g., 1.00% on first $1M, 0.75% on next $4M, 0.50% above $5M)",
            "Flat percentage — single rate across all AUM",
            "Fixed dollar — flat annual fee regardless of asset level (common in financial planning)",
            "Project or hourly — used for specific engagements (estate planning project, one-time financial plan)",
            "Performance fee — fee tied to performance above a benchmark; subject to SEC rules requiring qualified clients and specific structure",
            "Bundled vs unbundled — fee covers all services or itemized by service"
          ]},
          {"type": "subheading", "content": "Calculation method"},
          {"type": "paragraph", "content": "The advisory agreement specifies the calculation method. Common: fees calculated quarterly based on the average daily balance over the prior quarter; fees calculated based on the period-end balance; fees calculated based on the period-start balance; fees calculated as a daily accrual based on each day's balance. Different methods produce slightly different fee amounts for the same client. Whatever the method, it must be applied consistently and disclosed clearly."},
          {"type": "subheading", "content": "Pro-rating for partial periods"},
          {"type": "paragraph", "content": "When clients are added or terminated mid-period, the fee for the period is pro-rated. New client added on day 20 of a 90-day quarter pays 70/90ths of the quarterly fee. Terminated client gets the same treatment in reverse — billed only for the days they were a client during the period. Pro-rating must be documented in the advisory agreement and applied consistently."},
          {"type": "subheading", "content": "Fee debits from client accounts"},
          {"type": "paragraph", "content": "Most RIAs are authorized in the advisory agreement to instruct the custodian to debit fees directly from client accounts. The custodian processes the debit on the scheduled date; the client sees the debit on their statement. The custodian sends an automated 'fee debit' notification to the client (or to the advisor for relay) confirming the fee amount and source account. This is one of the limited-authority transactions allowed without per-event client consent — but the authority must be clearly granted in the advisory agreement and the firm must have processes to ensure fees are calculated correctly."},
          {"type": "callout", "kind": "warn", "content": "Overcharging clients on fees, even by small amounts, is one of the most common findings in SEC and state regulatory exams. The error usually comes from incorrect fee schedule application, not bad intent — but the consequence (restitution, fines, reputational damage) is real. Reconcile fees carefully every billing cycle."},
          {"type": "subheading", "content": "Fee reconciliation"},
          {"type": "paragraph", "content": "Each billing cycle, the firm should reconcile: the expected fee (calculated from the agreement and AUM); the fee invoice generated by the system; the fee debited at the custodian; the revenue recognized in the firm's accounting. All four numbers should agree. Discrepancies require investigation: is the AUM source correct, is the rate schedule current, are pro-rations correct, did the custodian process the debit correctly. The fee reconciliation is typically run by operations or compliance, with sign-off after every billing cycle."},
          {"type": "subheading", "content": "Form ADV Part 2 alignment"},
          {"type": "paragraph", "content": "The fee schedule actually applied must match the fee disclosure in the firm's Form ADV Part 2. If the firm has different rate cards for different client segments, all of them must be disclosed. If fees are negotiable, the practice and basis must be disclosed. A regulator comparing a client's actual billed fees against the firm's Form ADV looking for unexplained discrepancies is a common audit pattern. Keep alignment tight."},
          {"type": "case_study", "title": "The pro-ration that nobody caught", "scenario": "A client terminated the relationship on March 15. The firm's quarterly billing process ran on March 31 and billed the full quarter's fee for January 1 - March 31. The client noticed: 'I terminated mid-March, why is the fee for the full quarter?' The apprentice investigated: the billing system was not configured to apply pro-ration for the termination month. Total over-billing: $1,234. Resolution: the firm refunded the over-billed amount immediately, communicated transparently with the client (who appreciated the prompt fix and stayed within the firm's friend network), and updated the billing configuration to handle terminations correctly going forward. The compliance officer also reviewed the prior 12 months of terminations to identify other clients who may have been similarly over-billed; found two other instances and processed refunds.", "discussion": "The error was small in any single case but systemic across the firm. Without the client's question and the apprentice's investigation, the issue would have persisted. Process fix: terminations now trigger an automatic pro-rated billing calculation; compliance reviews terminations monthly. The cost of operational fix is much lower than the cost of an SEC finding."}
        ]
      },
      {
        "id": "lesson-4",
        "title": "Processing Corporate Actions and Income",
        "summary": "Corporate actions and income distributions require active operational management. Mishandling them creates tax errors, reporting errors, and client confusion.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "Securities held in client accounts generate a steady stream of events that require operational handling: dividends, interest, return of capital distributions, stock splits, spin-offs, mergers, tender offers, rights offerings. Some of these are passive (the custodian processes automatically and the PMS reflects the result). Others require election decisions (a tender offer, a merger consideration choice between cash or stock). All require accurate reflection in records, correct tax treatment, and clear client communication where appropriate."},
          {"type": "subheading", "content": "Passive corporate actions"},
          {"type": "paragraph", "content": "Most corporate actions are passive — the custodian processes them automatically and the PMS picks up the result. Cash dividends post to the client's cash balance. Stock dividends create new shares. Stock splits adjust position quantities and per-share basis. Return of capital reduces basis. These do not require advisor action. They do require reconciliation (Lesson 2) to ensure the PMS reflects what the custodian shows."},
          {"type": "subheading", "content": "Active corporate actions — election decisions"},
          {"type": "paragraph", "content": "Some corporate actions present the client with a choice: accept a tender offer or hold the shares; choose cash or stock in a merger; exercise or sell warrants; participate in or skip a rights offering. The custodian notifies the firm of the action with a deadline. The firm has to decide (within authority granted) or coordinate with the client to decide. Defaults vary: tender offers default to non-participation (you keep the shares); rights offerings default to non-exercise (the rights expire); merger elections often default to a specific option per the merger documents."},
          {"type": "subheading", "content": "Income distributions and tax characterization"},
          {"type": "paragraph", "content": "Income distributions from securities — dividends, interest, capital gain distributions from funds — are characterized for tax purposes by the security issuer or fund company. Same dollar amount can be characterized differently depending on its source. Common characterizations: ordinary dividends, qualified dividends (preferential tax treatment), short-term capital gain distributions (ordinary rates), long-term capital gain distributions (preferential rates), tax-exempt interest (federal-tax-free), foreign-source income (eligible for foreign tax credit), and return of capital (basis reduction, not income). Characterizations are finalized in January when the tax-year reporting completes, sometimes resulting in reclassification of distributions made during the year."},
          {"type": "subheading", "content": "January reclassifications"},
          {"type": "paragraph", "content": "Many mutual funds and ETFs reclassify some of their distributions in January, after the fact. A distribution paid as 'dividend' during the year may be reclassified to return of capital or to a different capital gain treatment when the fund's final tax allocations are determined. The reclassification can change client tax outcomes — sometimes significantly. The reconciliation process must pick up these reclassifications and update PMS records accordingly. CPAs preparing client returns need the final 1099 reflecting reclassifications, not the in-year preliminary characterizations."},
          {"type": "subheading", "content": "Dividends and DRIP"},
          {"type": "paragraph", "content": "Dividend reinvestment plans (DRIP) automatically reinvest cash dividends in additional shares of the dividend-paying security. Set per account and per security at the custodian. Two considerations: tax-loss harvesting requires turning off DRIP on the security being harvested (to prevent wash-sale through the reinvestment, per Module 24); systematic rebalancing benefits from turning off DRIP and letting dividends accumulate in cash to be directed toward underweight allocations. Many client accounts have DRIP enabled by default; reviewing and adjusting DRIP settings is part of account setup and annual review."},
          {"type": "subheading", "content": "Communicating corporate actions to clients"},
          {"type": "paragraph", "content": "Some corporate actions warrant client communication; many do not. Threshold: communicate to the client when the action requires a decision (tender offer with potential financial impact, merger with election choice), when the action materially changes the holding (large special dividend, significant spin-off), or when the action will be visible on the client's statement in a way that may prompt questions. Routine dividends and small distributions do not require communication. Use judgment; over-communicating creates noise, under-communicating creates surprises."},
          {"type": "case_study", "title": "The unexpected reclassification", "scenario": "In December, Devon's portfolio shows $14,200 in distributions from a REIT ETF, categorized at that point as 'qualified dividends.' In late January, the fund company issues final tax allocations: the $14,200 is actually 38% qualified dividends, 41% ordinary non-qualified dividends, 16% return of capital, and 5% long-term capital gains. The PMS picks up the reclassification through the custodian's updated reporting. Devon's tax outlook changes meaningfully — what looked like all preferential-rate income includes substantial ordinary rate income. The apprentice notifies Devon and his CPA: 'The REIT ETF distribution characterization has been finalized differently than initially reported. Your final 1099 will reflect $5,400 in qualified dividends instead of $14,200, with the remainder in ordinary dividends, ROC, and capital gain distributions. Tax impact is approximately $1,800 higher than the December projection. Updated planning attached.'", "discussion": "REITs and certain other funds reclassify substantially in January. Without picking up the reclassification, Devon's tax projection would have been materially wrong. The CPA needs the final 1099 to file correctly. The apprentice's role: detect the reclassification, communicate the impact, update plans accordingly. Operational discipline matters at tax time."}
        ]
      },
      {
        "id": "lesson-5",
        "title": "Operations Controls and Segregation of Duties",
        "summary": "Operations controls are how a firm prevents errors and fraud through structural process design. Even at small firms, the principles can be applied with discipline.",
        "read_time": "9 min read",
        "blocks": [
          {"type": "paragraph", "content": "A firm's operational integrity depends on more than individual diligence — it depends on the structural controls that catch errors before they propagate. Segregation of duties (no one person controls the entire chain of a high-risk operation), independent review (a second set of eyes on consequential items), and audit trails (every action documented) are the three pillars of operational control. At larger firms, these are formalized by entire operations departments. At smaller firms, the principles still apply — implemented with discipline rather than scale."},
          {"type": "subheading", "content": "Segregation of duties — the principle"},
          {"type": "paragraph", "content": "Segregation of duties means that no single person should control all phases of a sensitive operation. The classic example: the person who authorizes a payment should not also be the person who initiates it, and neither should be the person who reconciles the bank statement. If all three are the same person, that person can divert funds and cover it up. With segregation, the diversion would require collusion across multiple people — much harder to execute and easier to detect."},
          {"type": "subheading", "content": "Common segregations in advisory operations"},
          {"type": "list", "items": [
            "Trade authorization vs trade execution — the apprentice may prepare the trade; the trader executes; the operations team reconciles",
            "Fee calculation vs fee review — the system calculates; operations or compliance reviews; finance recognizes revenue",
            "Account opening vs disbursement authority — the person who opens an account should not be the same person who authorizes withdrawals from it",
            "Wire initiation vs wire approval — wires above a threshold require approval from a second person",
            "Personal trading vs trade execution — anyone who places client trades has constrained personal trading per firm policy"
          ]},
          {"type": "subheading", "content": "Independent review"},
          {"type": "paragraph", "content": "Beyond segregation, certain operations should have independent review even if not strictly segregated. Examples: a senior advisor reviewing all new account openings before they go live; compliance reviewing all fee calculations periodically; operations reviewing all corporate action elections; trading reviewing all suitability documentation on certain product types. Independent review is not bureaucracy — it is the structural mechanism for catching errors that the originator missed."},
          {"type": "subheading", "content": "Audit trails"},
          {"type": "paragraph", "content": "Every significant action — trade, transfer, fee debit, account change, document update — should generate a record showing who did it, when, and why. Modern PMS and CRM systems automate audit trails for actions performed within them. Actions performed outside (manual paperwork, phone calls, emails) need to be recorded manually. The audit trail serves three purposes: regulatory compliance, dispute resolution, and continuous improvement. Years later, the audit trail is what allows the firm to reconstruct what happened and why."},
          {"type": "subheading", "content": "Compliance calendar"},
          {"type": "paragraph", "content": "Most firms maintain a compliance calendar — scheduled recurring reviews, filings, and certifications. Examples: quarterly Form ADV updates if applicable; annual Form ADV re-filing; annual review of all client suitability documents; quarterly review of personal trading; semi-annual review of soft dollar arrangements; annual review of business continuity plan. Apprentices typically do not own the compliance calendar but may contribute to specific items. Knowing the cadence and respecting the deadlines is part of professionalism."},
          {"type": "subheading", "content": "Operational risk assessment"},
          {"type": "paragraph", "content": "Periodically — annually for most firms — the firm should conduct an operational risk assessment: what are the operations we perform, where are the failure modes, what controls do we have, and where are the gaps? The assessment is the structured version of the question 'what could go wrong here, and what would we do if it did.' Outputs include process improvements, control additions, and training priorities. Small firms can do this in a few hours; large firms have entire teams dedicated to it. Either way, the discipline keeps controls aligned with evolving risk."},
          {"type": "subheading", "content": "Errors as learning opportunities"},
          {"type": "paragraph", "content": "When an operational error occurs, the response should include not only the immediate correction (Module 23, Module 17) but a structured retrospective: what happened, why was it not caught, what process change would prevent recurrence. The retrospective should be blameless — focused on system improvement, not individual fault. Errors that lead to better systems are better than errors that lead to silence. The firm's error log, reviewed quarterly, reveals patterns: which operations produce the most errors, which controls are working, where new controls are needed."},
          {"type": "callout", "kind": "key", "content": "Strong operations are not the absence of errors — they are the system that detects errors quickly, corrects them cleanly, and continuously improves to reduce their frequency. Treat every error as data about how to improve."},
          {"type": "case_study", "title": "Building controls at a growing firm", "scenario": "A small RIA has grown from 1 advisor to 3 in 18 months, adding an operations associate and an apprentice. The founder previously handled all operations personally; segregation of duties was structurally impossible with one person. With the team in place, the founder works with the operations associate to build the first formal controls: trades placed by advisors are reviewed end-of-day by operations; fee calculations are reviewed quarterly by compliance (which they outsource to a consultant); wires over $50K require two-person approval; the apprentice runs daily reconciliation with senior review of any exception over $5K. The firm documents the controls in a written operations manual.", "discussion": "None of this is exotic. All of it is the standard playbook applied at the firm's scale. The investment in formalization pays back in fewer errors, faster detection of any that occur, and a defensible compliance posture as the firm grows further. Operational maturity is what enables scale."},
          {"type": "divider"},
          {"type": "paragraph", "content": "Next module: Compliance Workflows. The regulatory framework that governs day-to-day operations and the documentation that proves we are operating within it."}
        ]
      }
    ],
    "quiz": {
      "passing_score": 80,
      "questions": [
        {"id": "q1", "prompt": "When the firm's portfolio management system and the custodian's records disagree, the appropriate response is to:", "options": ["Use whichever number is higher", "Investigate, identify the cause, and fix the system that is wrong — custodial records are the official truth", "Average the two", "Use the PMS number for client reports"], "correct": 1, "explanation": "Custodian records are the official truth. Reconciliation aligns the PMS to the custodian, with documented adjustments."},
        {"id": "q2", "prompt": "Daily reconciliation catches errors when:", "options": ["They are cheapest to fix; lingering errors compound and surface as larger incidents", "There is nothing else to do", "Required by SEC rules", "Only at year-end"], "correct": 0, "explanation": "Speed of detection determines cost of correction. Daily reconciliation flags exceptions while they are still single-account fixes."},
        {"id": "q3", "prompt": "A return of capital (ROC) distribution affects the security's:", "options": ["Tax bracket", "Cost basis — it is treated as a return of the investor's basis rather than income, reducing basis", "Dividend yield", "Sector classification"], "correct": 1, "explanation": "ROC reduces basis rather than producing current income. When the security is eventually sold, the gain is larger because of the basis reduction."},
        {"id": "q4", "prompt": "January reclassifications by mutual funds and ETFs can affect:", "options": ["Only the fund company", "Client tax outcomes — distributions paid during the year may be re-characterized when final tax allocations are determined, changing whether amounts were dividends, ROC, capital gains, etc.", "Only IRA accounts", "Only foreign investments"], "correct": 1, "explanation": "January reclassifications can materially change client tax outcomes. CPAs need final 1099s reflecting the reclassifications; preliminary in-year characterizations are not final."},
        {"id": "q5", "prompt": "A position quantity discrepancy between PMS and custodian is:", "options": ["A routine timing break that can wait", "A high-priority break that should be investigated immediately and not left overnight without explanation", "Always the custodian's fault", "Usually a tax-only issue"], "correct": 1, "explanation": "Position discrepancies can indicate real operational failures — missing trades, transfer errors, manual mistakes. Escalation is appropriate when not resolved same-day."},
        {"id": "q6", "prompt": "Most advisory fees are calculated and debited based on:", "options": ["Client request each quarter", "Authority granted in the advisory agreement, with the custodian processing the debit on the scheduled date based on the firm's calculation", "Custodian discretion", "Performance only"], "correct": 1, "explanation": "Direct debit authority is granted in the advisory agreement and processed by the custodian. The firm calculates the fee; the custodian debits; the client sees both."},
        {"id": "q7", "prompt": "Overcharging clients on advisory fees, even small amounts, is:", "options": ["Generally minor and unenforced", "One of the most common findings in SEC and state regulatory exams; restitution and penalties are real", "Required for revenue maintenance", "Disclosed in marketing materials"], "correct": 1, "explanation": "Fee errors are a recurring regulatory finding. Even when unintentional, the consequence is restitution, fines, and reputational damage."},
        {"id": "q8", "prompt": "Segregation of duties means:", "options": ["Each advisor specializes in one area", "No single person should control all phases of a sensitive operation — separation creates a check that requires collusion to defeat", "All trades go through one person for consistency", "Different fees for different services"], "correct": 1, "explanation": "Segregation makes single-person fraud or error harder by ensuring multiple people see different parts of a process. Standard control in financial operations."},
        {"id": "q9", "prompt": "When a client terminates the advisory relationship mid-quarter, the fee for that quarter should be:", "options": ["Charged in full per the agreement", "Pro-rated for the days the client was actually a client during the period, per the advisory agreement", "Waived entirely", "Increased to cover transition costs"], "correct": 1, "explanation": "Pro-ration is the standard practice and must be documented in the advisory agreement. Failing to pro-rate is a common over-billing pattern flagged in exams."},
        {"id": "q10", "prompt": "Tender offers in client accounts where no election is made typically default to:", "options": ["Acceptance of the offer", "Non-participation — the client keeps the shares", "Cash exchange at the lowest offered price", "Court determination"], "correct": 1, "explanation": "Tender offers require affirmative election to participate. Without election, the client retains the shares."},
        {"id": "q11", "prompt": "Audit trails for operational actions serve which purposes?", "options": ["Only regulatory compliance", "Regulatory compliance, dispute resolution, and continuous improvement", "Internal marketing", "Tax preparation only"], "correct": 1, "explanation": "Audit trails enable reconstruction of what happened, defense in disputes, and pattern analysis for process improvement. Multi-purpose discipline."},
        {"id": "q12", "prompt": "After an operational error, the most valuable response is:", "options": ["Identifying who to blame", "A blameless retrospective focused on what process change would prevent recurrence, plus immediate client correction", "Hiding the error from compliance", "Reducing the affected client's fees as compensation"], "correct": 1, "explanation": "Blameless retrospectives produce systemic improvements. Blame produces silence and recurrence. Combine the immediate client correction with the structural fix."}
      ]
    }
  }
  $jsonb$::jsonb,
  updated_at = now()
where module_number = 26;
