-- ============================================================================
-- GIC APPRENTICE LMS — MODULE 21 CONTENT
-- Asset Allocation & Rebalancing
-- ============================================================================
update public.modules set
  title = 'Asset Allocation & Rebalancing',
  competency_id = 'OJL-12',
  ri_hours = 0,
  ojl_hours = 100,
  short_description = 'Maintain a portfolio''s design across years of market movement — choosing a rebalancing methodology, executing trades tax-aware, and adjusting allocations as the client''s life evolves.',
  learning_objectives = ARRAY[
    'Compare strategic, tactical, and dynamic asset allocation approaches',
    'Implement calendar-based, threshold-based, and hybrid rebalancing methodologies',
    'Execute rebalancing trades in a tax-aware manner across account types',
    'Adjust target allocations across the life cycle without overreacting to short-term events',
    'Maintain documentation of allocation changes and the reasoning behind them'
  ],
  content = $jsonb$
  {
    "lessons": [
      {
        "id": "lesson-1",
        "title": "Strategic, Tactical, and Dynamic Allocation",
        "summary": "There are three philosophies of how to set and adjust asset allocation. Most retail planning lives at the strategic end of the spectrum, but understanding all three is part of the work.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "Asset allocation is the most-studied decision in portfolio management, and the most consequential. Multiple academic studies — most famously Brinson, Hood, and Beebower (1986) — have estimated that asset allocation explains the majority of the variation in long-term portfolio returns. The follow-on debate about whether the figure is 90%+ or closer to 40% misses the more practical point: how you allocate matters more than which specific funds you pick within an allocation. Three broad philosophies define how practitioners approach the allocation question."},
          {"type": "subheading", "content": "Strategic asset allocation"},
          {"type": "paragraph", "content": "Strategic allocation sets a long-term target based on the client's situation — goals, time horizon, risk capacity and tolerance, return needs — and maintains that target with discipline through market cycles. The allocation changes when the underlying client situation changes (retirement, major inheritance, time horizon shift), not when the planner forms a market view. Strategic allocation is the dominant philosophy in retail planning because it is consistent with fiduciary duty, supported by empirical evidence, and avoids the trap of timing markets badly."},
          {"type": "subheading", "content": "Tactical asset allocation"},
          {"type": "paragraph", "content": "Tactical allocation deviates from a strategic baseline based on short- to medium-term market views — overweighting an asset class that appears attractive on valuation or momentum grounds, underweighting one that appears expensive or vulnerable. Tactical deviations are typically constrained — say ±10% from the strategic target — and meant to add modest returns through skillful timing. Empirical evidence on tactical allocation skill is mixed. Most retail tactical strategies have not beaten their strategic benchmark after costs."},
          {"type": "subheading", "content": "Dynamic asset allocation"},
          {"type": "paragraph", "content": "Dynamic allocation systematically adjusts based on rules — a glide path that grows more conservative as retirement approaches, a volatility target that reduces equity exposure when realized volatility spikes, or factor exposures that change with macro conditions. Target-date funds are the most common form of dynamic allocation. The defining feature is that the allocation changes are systematic and rules-based, not discretionary."},
          {"type": "callout", "kind": "key", "content": "For most clients in most situations, a disciplined strategic allocation with periodic rebalancing outperforms attempts to be tactical. Humility about market timing is a feature of good planning, not a weakness."},
          {"type": "subheading", "content": "Glide paths"},
          {"type": "paragraph", "content": "A glide path is a pre-specified schedule of how the allocation changes over time, usually as retirement approaches. A common pattern: 90/10 in the 30s, gliding down to 60/40 at age 60, then 40/60 at age 70, with continued small reductions into the late 70s. Glide paths can be embedded in target-date funds or implemented manually across the portfolio. The advantage is automatic risk reduction as the time horizon shortens; the cost is loss of customization to the individual client's situation."},
          {"type": "subheading", "content": "Equity glide paths in retirement — the contrarian view"},
          {"type": "paragraph", "content": "Wade Pfau and Michael Kitces have published research arguing that, for some retirees, an equity allocation that rises through retirement — starting lower at the retirement date when sequence-of-returns risk is highest, then rising as the portfolio survives the early withdrawal years — outperforms a conventional declining glide path. The intuition is that the most fragile moment of a retirement portfolio is the first decade; once that is past, longer horizons can absorb more risk. This is not the standard approach, but it is part of the modern conversation about glide path design."},
          {"type": "case_study", "title": "Choosing the philosophy for Marcus and Tasha", "scenario": "Marcus and Tasha are 35 and 33, with a 30-year retirement horizon and a 15-year college funding horizon for their two children. The apprentice recommends a strategic asset allocation: 80/20 for retirement assets, 60/40 for the 529s (which will be drawn down starting in 8 years). No tactical deviations. A glide path is set for the retirement allocation: 80/20 holds until age 50, then begins gliding 1 percentage point per year toward 60/40 by age 70. The 529 glide path is sharper because the time horizon is shorter — 60/40 today, becoming 40/60 five years before the first child's enrollment, then 20/80 in the year before enrollment.", "discussion": "The apprentice did not attempt to forecast equity returns or time the next recession. They built a strategic structure with rules for how it evolves. Marcus and Tasha know what to expect for the next 35 years, and the structure does not depend on the apprentice (or any successor) being a good market timer."}
        ]
      },
      {
        "id": "lesson-2",
        "title": "Rebalancing Methodology — Calendar, Threshold, Hybrid",
        "summary": "Once an allocation is set, the work shifts to maintaining it. The three main methodologies have measurable differences in trading frequency, tax cost, and effectiveness.",
        "read_time": "11 min read",
        "blocks": [
          {"type": "paragraph", "content": "Markets move every day. Asset class returns differ. A portfolio that starts the year at 60/40 will not end the year at 60/40 — it will be 65/35 if equities outperformed, 54/46 if bonds did. Rebalancing is the practice of bringing the portfolio back toward its target. The methodology — when and by how much — has been studied extensively."},
          {"type": "subheading", "content": "Calendar-based rebalancing"},
          {"type": "paragraph", "content": "Rebalance to target on a fixed schedule — quarterly, semi-annually, or annually. Annual is the most common in retail planning because it generates fewer taxable events in taxable accounts and aligns with the natural rhythm of annual reviews. Quarterly rebalancing can produce slightly better risk control but introduces more trading and more potential tax cost. Calendar-only methodology will sometimes trade unnecessarily (rebalancing a portfolio that is barely off target) and sometimes fail to act (waiting for the next scheduled date even after significant drift)."},
          {"type": "subheading", "content": "Threshold-based rebalancing"},
          {"type": "paragraph", "content": "Rebalance when any asset class moves outside a specified band around its target — typically ±5 percentage points for major asset classes and ±3 for sub-classes. Threshold-based rebalancing responds to actual drift and tends to trade only when drift is meaningful. The downside is operational — somebody has to be watching for breaches. In practice, threshold methodology requires either software monitoring or a disciplined periodic check."},
          {"type": "subheading", "content": "Hybrid rebalancing"},
          {"type": "paragraph", "content": "Check on a regular schedule (typically quarterly or annually) and rebalance only if outside the threshold band. This is the methodology most institutional and many sophisticated retail practitioners use because it captures the discipline of regular review without forcing trades when none are needed. A 2015 Vanguard research paper concluded that annual checks with 5% bands produced similar risk control as more frequent rebalancing at meaningfully lower cost."},
          {"type": "callout", "kind": "key", "content": "Default starting policy for most retail clients: annual review with 5% threshold for major asset classes and 3% for sub-classes. Adjust based on tax sensitivity and operational capability."},
          {"type": "subheading", "content": "What rebalancing actually does"},
          {"type": "paragraph", "content": "Two effects, in order of importance. First — and primarily — rebalancing maintains the risk profile the client signed up for. A 60/40 portfolio that has drifted to 70/30 is now a different portfolio with different risk than was agreed. Without rebalancing, drift accumulates: a 60/40 portfolio left untouched through the 2010s would have ended the decade closer to 80/20 simply from equity outperformance. The client would now be in a portfolio they did not choose. Risk maintenance is the non-negotiable function."},
          {"type": "paragraph", "content": "Second — and a smaller effect — rebalancing produces a modest 'rebalancing bonus' from systematically selling what is up and buying what is down. The magnitude is small, often 10-30 basis points per year, and depends on volatility and correlation between asset classes. It can also be zero or negative over some periods. Do not oversell the rebalancing bonus to clients. Sell the risk-management function, which is the real reason."},
          {"type": "subheading", "content": "How to rebalance — sell or use new contributions"},
          {"type": "paragraph", "content": "There are two ways to rebalance. The first is to sell from overweighted asset classes and buy underweighted ones — a 'transactional' rebalance. The second is to redirect new contributions or distributions toward underweighted classes, drifting the allocation back to target over time without selling anything. The second method is preferable in taxable accounts because it avoids realizing gains. In tax-advantaged accounts, either is fine. A portfolio with regular cash flows can stay reasonably close to target through contribution-direction alone if the cash flows are large enough relative to drift."},
          {"type": "case_study", "title": "Naomi's first rebalancing event", "scenario": "Eight months after construction, Naomi's portfolio shows drift: U.S. equity at 56% vs 50% target (within 5% band), international developed at 14% vs 18% target (outside the 3% sub-class threshold), emerging at 5% vs 7% (outside the 3% threshold), fixed income proportions also within bands. The apprentice triggers a sub-class rebalance: sell ~3% of U.S. equity in Naomi's Roth IRA (no tax cost), buy international developed and emerging to restore targets. Total trade: $11,000. No tax cost. Risk profile back at target.", "discussion": "Notice — the apprentice executed in the Roth to avoid tax. They did not over-trade the taxable account. The risk profile is restored. The IPS specified the bands; the bands triggered the action; the action was tax-aware. Process produced the outcome."}
        ]
      },
      {
        "id": "lesson-3",
        "title": "Tax-Aware Rebalancing",
        "summary": "Rebalancing in tax-deferred accounts has no tax cost. Rebalancing in taxable accounts can be expensive. The skill is in achieving the rebalance with minimal tax friction.",
        "read_time": "11 min read",
        "blocks": [
          {"type": "paragraph", "content": "A rebalancing trade in a taxable account that sells appreciated holdings triggers capital gains tax. The tax cost can erode much or all of the rebalancing bonus and, for clients in high brackets, can make naive rebalancing actively harmful. Tax-aware rebalancing methodology addresses this without sacrificing the risk-management function."},
          {"type": "subheading", "content": "Order of operations for tax efficiency"},
          {"type": "numbered", "items": [
            "First, rebalance in tax-advantaged accounts (IRA, 401(k), Roth) where trades have no tax cost",
            "Second, direct new contributions toward underweight asset classes to drift the allocation back without selling",
            "Third, direct dividends and distributions from overweight classes to underweight classes (turn off automatic reinvestment when needed)",
            "Fourth, if income from the portfolio is being taken anyway, take it preferentially from overweight asset classes",
            "Fifth, only when the above are insufficient, sell in taxable accounts — and even then, preferentially harvest losses or sell lots with the highest cost basis"
          ]},
          {"type": "subheading", "content": "The 'rebalance in the IRA' technique"},
          {"type": "paragraph", "content": "If the household has $200K in a taxable brokerage and $200K in an IRA, and the portfolio is overweight equity, the apprentice does not need to sell equity in the taxable account. Instead, sell equity and buy bonds inside the IRA — same effect on overall allocation, zero tax cost. This requires viewing the household portfolio as a single allocation across accounts (per Module 19) rather than rebalancing each account independently."},
          {"type": "subheading", "content": "Tax lot selection"},
          {"type": "paragraph", "content": "When selling securities in a taxable account, the cost basis method determines which specific tax lots are sold. Common methods: FIFO (first-in, first-out, oldest lots first), LIFO (last-in, first-out), and Specific Identification (you choose which lots). For tax-aware rebalancing, Specific Identification is generally the best method — it allows selling lots with higher cost basis (less gain) or with losses (offsetting other gains). Most custodians default to FIFO; switch to Specific ID for taxable accounts where rebalancing happens."},
          {"type": "callout", "kind": "do", "content": "On any taxable account where active management will occur, set the default cost basis method to Specific Identification, not FIFO. This single setting can save thousands in taxes over a portfolio's life."},
          {"type": "subheading", "content": "Wash-sale awareness"},
          {"type": "paragraph", "content": "If you sell a security at a loss in a taxable account and buy a 'substantially identical' security within 30 days before or after the sale (in any account, including IRAs and a spouse's accounts), the loss is disallowed under the wash-sale rule. Wash-sale rules apply to rebalancing trades too. If you sell VTI at a loss to harvest, you cannot buy VTI back within 30 days. You can buy a similar-but-not-substantially-identical fund (say, ITOT instead of VTI), or wait 31 days. Track this carefully. Wash-sale violations are easy to inadvertently trigger across linked accounts."},
          {"type": "subheading", "content": "Long-term vs short-term capital gains"},
          {"type": "paragraph", "content": "If selling is required in a taxable account, prefer long-term gains over short-term gains where possible. Long-term gains (assets held more than one year) are taxed at preferential rates (0/15/20% federal); short-term gains are taxed at ordinary rates. A tax lot that is 11 months and 3 weeks old can become long-term if you wait three more weeks; if the timing allows and the drift is not extreme, the wait is worth thousands of dollars in many situations."},
          {"type": "subheading", "content": "Worked example — Devon's rebalance scenario"},
          {"type": "paragraph", "content": "Devon's household portfolio is overweight equity by 8 percentage points after a strong equity year. His taxable brokerage holds appreciated equity ETF positions with substantial gains. His SEP-IRA holds bonds. Rather than sell equity in the taxable account (triggering long-term gains), the apprentice sells bonds in the SEP-IRA and buys equity inside the SEP-IRA. Wait — that increases equity, not decreases. Correct move: sell equity inside the SEP-IRA (no tax cost) and buy bonds inside the SEP-IRA. Net effect on the household portfolio: equity down, bonds up, no taxable event. The taxable account stays untouched; rebalancing happens in the tax-advantaged sleeve."},
          {"type": "callout", "kind": "key", "content": "When rebalancing across a household with multiple account types, the question is not 'what trades happen in each account' but 'what trades happen at all, and where do they have the lowest tax cost.' Always think at the household level."}
        ]
      },
      {
        "id": "lesson-4",
        "title": "Adjusting Allocation Across the Life Cycle",
        "summary": "Allocations should evolve as clients age and their goals shift. The hard part is making the changes for the right reasons and at the right pace.",
        "read_time": "10 min read",
        "blocks": [
          {"type": "paragraph", "content": "An asset allocation that is right for a 32-year-old accumulator is not right for the same person at 65, and is definitely not right at 80. But the changes should happen for the right reasons (time horizon shortening, capacity changing, goals evolving) and at the right pace (gradual, in advance of need, not in reaction to recent markets). This lesson covers how to think about life cycle allocation changes."},
          {"type": "subheading", "content": "When to make allocation changes"},
          {"type": "list", "items": [
            "Major life events that change the underlying facts — marriage, divorce, birth of child, death of spouse, significant inheritance, business sale, retirement",
            "Time horizon meaningfully shortening — within 5-7 years of a known cash need (retirement, college, home purchase)",
            "Risk capacity changing — job loss reducing income stability, health condition altering longevity expectations, large change in fixed expenses",
            "Risk tolerance demonstrably and persistently changing — a single panic episode does not constitute a tolerance change; a pattern of distress over multiple market events does",
            "Goals fundamentally shifting — early retirement decision, decision to extend working years, large new philanthropic objective"
          ]},
          {"type": "subheading", "content": "When NOT to make allocation changes"},
          {"type": "list", "items": [
            "After a strong year in any asset class ('We should add more emerging markets, they were up 22% last year')",
            "After a weak year in any asset class ('Let's reduce equity, the market is down 18%')",
            "Because a friend, neighbor, or media commentator suggested a change",
            "Because of an upcoming election or geopolitical event (almost always a fool's errand)",
            "Because the client is briefly anxious without a fundamental change in their situation"
          ]},
          {"type": "subheading", "content": "Pre-retirement glide path"},
          {"type": "paragraph", "content": "The 5-10 years before retirement are the most consequential glide path period. Sequence-of-returns risk peaks at and just after retirement — a large drawdown in the early years of withdrawal can permanently impair the plan. A typical pre-retirement glide path: starting from say 70/30 at age 55, reduce equity by 1 percentage point per year through age 65, ending at 60/40 (or lower depending on the specific plan). The pre-retirement glide creates a 'bond tent' — a build-up of fixed income exposure heading into retirement, which is partially drawn down during the early withdrawal years."},
          {"type": "subheading", "content": "In-retirement allocation"},
          {"type": "paragraph", "content": "Once retirement is underway, allocation evolves more slowly. A 65-year-old retiree at 60/40 may stay at 60/40 through their early 70s, then drift down to 50/50 or 45/55 by their late 70s. Maintaining sufficient equity exposure is important — a 30-year retirement requires real growth to outpace inflation. Going too conservative too quickly is a real failure mode for retirees."},
          {"type": "callout", "kind": "warn", "content": "The most common allocation mistake in retirement is overshooting toward conservatism. A 65-year-old at 30/70 may feel safer but is taking enormous inflation risk over a 25-30 year horizon. Equity is not optional in retirement — its share is."},
          {"type": "subheading", "content": "Late-life allocation and capacity questions"},
          {"type": "paragraph", "content": "In the final stage of a long retirement, allocation may need to shift in response to capacity concerns. If a client in their late 80s is showing cognitive decline, complex investments become harder to manage. Simplification is a value of its own at this stage. A portfolio of three broad ETFs is easier for an aging client (or a surrogate decision-maker, or an executor) to oversee than a portfolio of 30 holdings. Sometimes the right allocation change is a simplification, not a directional shift in risk."},
          {"type": "case_study", "title": "Marcus and Tasha — the year of the bond tent decision", "scenario": "Marcus is now 48. He has discussed wanting to retire at 60. The apprentice walks through the pre-retirement glide path: starting at 75/25, glide down 1 percentage point per year over the next decade, ending at 65/35 at retirement. The apprentice documents the rationale in the IPS update. Tasha at 46 has similar timing but slightly different risk tolerance — she wants a steeper glide. Negotiated landing: both move to 75/25 today as the household, glide to 65/35 over the next twelve years, with a year-by-year schedule written into the IPS.", "discussion": "The schedule is durable. It does not depend on the apprentice being a market timer. The clients know exactly what to expect each year. When markets move, the schedule does not change — only the underlying facts can change it."}
        ]
      },
      {
        "id": "lesson-5",
        "title": "Documenting Allocation Changes and Rebalancing Activity",
        "summary": "Every allocation change, every rebalancing event, every IPS update should leave a paper trail. The documentation is the institutional memory that protects the plan and the relationship.",
        "read_time": "9 min read",
        "blocks": [
          {"type": "paragraph", "content": "An allocation decision that is not documented is a decision that cannot be defended later. Years from now, a client asking 'why did we shift to 65/35 when I was 55?' or a regulator asking 'what was the rationale for the rebalancing trade on March 14?' deserves an answer that can be reconstructed from the file. The documentation discipline from Module 20 (investment decisions) extends to allocation changes and rebalancing activity."},
          {"type": "subheading", "content": "The allocation change memo"},
          {"type": "paragraph", "content": "Any change to the target allocation should be accompanied by a short memo capturing: what changed, why it changed (the specific fact in the client's situation that drove the change), what was considered, the resulting new target allocation, and the date and signatures. Update the IPS to reflect the change. Send the client a summary letter or email confirming the change and the reasoning."},
          {"type": "subheading", "content": "Rebalancing trade documentation"},
          {"type": "paragraph", "content": "Each rebalancing event should generate a record: the pre-trade allocation, the trades executed, the post-trade allocation, the rationale (which band was breached, what was the methodology), and any tax considerations. Most CRM and portfolio management systems automate much of this. The apprentice's job is to make sure the automation is on and the records are accurate."},
          {"type": "subheading", "content": "Annual rebalancing review"},
          {"type": "paragraph", "content": "Once a year — typically at the annual review with the client — the apprentice should pull a record of all rebalancing activity for the year, review whether the methodology worked as intended, and consider whether the bands or the methodology need adjustment. Did the threshold bands trigger too often? Too rarely? Were taxes managed effectively? Were there missed rebalancing opportunities? This review is part of the firm's continuous improvement, distinct from the client review but informing it."},
          {"type": "subheading", "content": "Behavioral discipline around documentation"},
          {"type": "paragraph", "content": "The temptation when markets are turbulent is to skip the documentation — 'just get the trades done.' Resist. The trades themselves take five minutes. The five additional minutes to document why creates the audit trail that protects the relationship. Time pressure is precisely when documentation matters most because it is the only record that the decision was deliberate and reasoned rather than reactive."},
          {"type": "callout", "kind": "do", "content": "Make the documentation step part of the trade workflow, not an afterthought. If the documentation has not been completed, the trade is not considered finished — same discipline as verifying completion in Module 17."},
          {"type": "subheading", "content": "Communication with the client"},
          {"type": "paragraph", "content": "Some firms communicate every rebalancing trade to clients in writing; others communicate only at annual reviews. The choice depends on client preference and firm policy. At minimum, any change to the target allocation or any significant rebalancing event (substantial dollar amount, significant tax impact, or out-of-cycle timing) should be communicated to the client promptly. Clients who learn about consequential changes in their portfolio months after the fact lose trust quickly. Clients who hear from their advisor as things happen build it."},
          {"type": "case_study", "title": "The year-end rebalancing letter", "scenario": "Each December, the apprentice writes a short year-end letter to each client recapping the year's rebalancing activity. For Naomi: '2025 year-end summary — your portfolio was rebalanced in March (sub-class drift in international developed and emerging markets, restored within bands) and in October (full annual rebalance back to target). Total taxable gains realized this year: $0 (all rebalancing executed in tax-advantaged accounts). Your target allocation of 75/25 remains unchanged. The next scheduled annual review is February 12.' Two paragraphs. Standard format across all clients. Time per client: 10 minutes.", "discussion": "Naomi knows what happened. The record exists in her file and in her email. The firm's institutional memory matches her own. Trust compounds, year over year, from small disciplines like this."},
          {"type": "callout", "kind": "key", "content": "Documentation is part of the work, not a chore added to it. The same minute spent capturing the why now saves an hour reconstructing it later."},
          {"type": "divider"},
          {"type": "paragraph", "content": "Next module: Performance Reporting. How to measure and communicate what the portfolio actually did, honestly and clearly."}
        ]
      }
    ],
    "quiz": {
      "passing_score": 80,
      "questions": [
        {"id": "q1", "prompt": "Strategic asset allocation is best described as:", "options": ["Active trading based on market views", "Setting a long-term target based on the client's situation and maintaining it with discipline through cycles", "Algorithmic trading based on momentum", "Switching to cash during downturns"], "correct": 1, "explanation": "Strategic allocation is the dominant retail approach — set the target from the client's situation, maintain it, change only when the underlying facts change."},
        {"id": "q2", "prompt": "Brinson, Hood, and Beebower's research is most often cited for showing that:", "options": ["Stock picking is the primary driver of returns", "Asset allocation explains the majority of variation in long-term portfolio returns", "Market timing reliably adds value", "Active management beats passive over time"], "correct": 1, "explanation": "BHB and subsequent studies put asset allocation at the center of return variation. The exact percentage is debated, but the practical implication — allocation matters more than security selection — is well established."},
        {"id": "q3", "prompt": "Hybrid rebalancing methodology is best described as:", "options": ["Rebalancing every month regardless of drift", "Checking on a regular schedule and rebalancing only if outside the threshold band", "Never rebalancing", "Rebalancing only after market crashes"], "correct": 1, "explanation": "Hybrid combines the discipline of scheduled review with the efficiency of acting only when drift is meaningful. Common default: annual check with 5% bands."},
        {"id": "q4", "prompt": "The primary function of rebalancing is to:", "options": ["Generate a rebalancing bonus", "Maintain the risk profile the client agreed to", "Time market tops and bottoms", "Maximize tax losses"], "correct": 1, "explanation": "Risk maintenance is the non-negotiable function. The rebalancing bonus exists but is secondary; do not oversell it to clients."},
        {"id": "q5", "prompt": "The first place to rebalance, all else equal, is:", "options": ["The taxable brokerage account", "Tax-advantaged accounts (IRA, 401(k), Roth) where trades have no tax cost", "By cash withdrawal", "Through margin trading"], "correct": 1, "explanation": "Tax-advantaged accounts allow rebalancing trades with zero tax cost. Always exhaust this option before selling in taxable accounts."},
        {"id": "q6", "prompt": "The wash-sale rule disallows a loss on a security if:", "options": ["The security is sold and bought back the same day", "A 'substantially identical' security is bought within 30 days before or after the sale, in any linked account", "The security is held more than one year", "The security pays a dividend"], "correct": 1, "explanation": "The 30-day window applies in both directions and across linked accounts (including IRAs and a spouse's accounts). Tracking this is essential during loss harvesting."},
        {"id": "q7", "prompt": "On a taxable account where active management will occur, the default cost basis method should be set to:", "options": ["FIFO", "LIFO", "Specific Identification, to allow choosing which tax lots to sell", "Average cost"], "correct": 2, "explanation": "Specific Identification lets you sell lots with the highest cost basis (smaller gains) or with losses to offset gains. The most tax-efficient method for active accounts."},
        {"id": "q8", "prompt": "A pre-retirement glide path — gradually reducing equity exposure in the years leading up to retirement — primarily addresses:", "options": ["Inflation risk", "Sequence-of-returns risk, which peaks at and just after retirement", "Interest rate risk", "Currency risk"], "correct": 1, "explanation": "A large drawdown in the early withdrawal years can permanently impair a retirement plan. The glide path reduces this risk by lowering equity exposure heading into and through the first years of withdrawal."},
        {"id": "q9", "prompt": "The most common allocation mistake in retirement is:", "options": ["Holding too much equity", "Overshooting toward conservatism, taking inflation risk over a 25-30 year horizon", "Rebalancing too often", "Holding international stocks"], "correct": 1, "explanation": "Going too conservative too quickly creates massive inflation risk across a long retirement. Equity is not optional in retirement — its share is."},
        {"id": "q10", "prompt": "An allocation change should generally NOT be made because:", "options": ["The client retired", "An asset class had a strong recent year and the client wants more", "The client received a large inheritance", "Time horizon meaningfully shortened"], "correct": 1, "explanation": "Performance-chasing is a destructive allocation behavior. Change allocation for changes in underlying facts (life events, time horizon, capacity, goals) — not for short-term performance."},
        {"id": "q11", "prompt": "If you sell VTI at a loss in a taxable account to harvest, you can:", "options": ["Buy VTI back the next day in your IRA", "Buy a similar-but-not-substantially-identical fund (like ITOT) immediately, or wait 31 days to buy VTI again", "Buy any fund you want immediately with no restriction", "Cannot harvest at all"], "correct": 1, "explanation": "Wash-sale rule applies across accounts including IRAs. Substitute with a non-substantially-identical fund or wait 31 days."},
        {"id": "q12", "prompt": "Documentation of a rebalancing event should include:", "options": ["Only the trade tickets", "Pre-trade allocation, trades executed, post-trade allocation, methodology rationale, and tax considerations", "Just the date", "Only what the client requested"], "correct": 1, "explanation": "Complete documentation lets a reviewer reconstruct the decision and confirm it followed the IPS. Treat documentation as part of the trade workflow."}
      ]
    }
  }
  $jsonb$::jsonb,
  updated_at = now()
where module_number = 21;
